### ISSUE TITLE
Spindles can Stack

### ISSUE THREAD

**Issue by PiordaNautor** [MysticMods/MysticalWorld#74] opened 2019-10-15 09:10 UTC
It is possible to stack a new Spindle with a damaged/used Spindle, and after separation, the original Spindle's durability is copied onto the new Spindle.

Edit: This is specifically through shift-clicking a Spindle on the crafting table into your inventory.
I have not tested if this is also a way to restore durability by using an undamaged spindle as the "Original."

**Comment by PiordaNautor** [comment] 2019-10-15 09:18
![image](https://user-images.githubusercontent.com/55087535/66818363-13037200-eef2-11e9-9f3d-ba2bc64e2337.png)
![image](https://user-images.githubusercontent.com/55087535/66818383-1860bc80-eef2-11e9-9cb8-872106113ddc.png)
![image](https://user-images.githubusercontent.com/55087535/66818394-1dbe0700-eef2-11e9-8236-1b47c8ee4904.png)

**Comment by duely** [comment] 2019-10-15 22:07
Oh wow! That's super weird and totally not supposed to happen. I'll have to dig into that a little deeper, thanks for the heads-up.

**Comment by duely** [comment] 2019-12-06 09:04
I'm not able to reproduce this in my current version, so I believe it should be fixed in the next release (if it isn't already).

**Closed by duely** 2019-12-06 09:04 UTC
Labels: bug
