### ISSUE TITLE
Crash when game try to load. (v1.12.2- 1.7.0)

### ISSUE THREAD

**Issue by DrakeTremor** [MysticMods/MysticalWorld#151] opened 2020-04-18 16:57 UTC
Game crash when it try to load the mod. It seems a problem with stackmap, idk about this stuff so prob is me prob is the mod either way i will share it to be sure.
Crash log:
https://paste.dimdev.org/unogoqezih.mccrash

**Comment by noobanidus** [comment] 2020-05-03 02:12
Sorry, I somehow missed this. I'm not actually sure what's happening. It honestly looks like something is corrupting the stackmap for `func_189214_a`, which is `getBrightnessForRender` using the MCP mappings, which appears to be something that some other mod is doing with ASM.

MysticalLib doesn't actually contain any ASM. Also, there's no reason why obtaining the constructor for a particle (ParticleGlow in this case, or Particle in general) would be calling `getBrightnessForRender`, which is only (in general) ever called through `renderParticle` rather than during particle creation/registration.

Specifically, `ifeq` moving to a branch that is attempting to access local variables is supposed to have a `stackmap` frame which says "hey, I want these local variables to be accessible at this point". The fact that this is occurring in `getBrightnessForRender` when we're just trying to create an instance of a class... I'm pretty sure it has to be another mod's ASM.

**Comment by noobanidus** [comment] 2020-05-03 02:14
(Please comment again if you still have issues or can reproduce with just MysticalLib and Blockcraftery -- you don't even appear to have Mystical World installed.)

**Closed** 2020-05-03 02:14 UTC
